apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  selector:
    matchLabels:
      app: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: jacobphelane/udagram-api-feed:latest
        env:
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_USERNAME
            value: postgres
          - name: POSTGRES_PASSWORD
            value: K#QdT)7G!UNFRT&V
          - name: POSTGRES_HOST
            value: postgres-database.cfg1ruu0beck.us-east-1.rds.amazonaws.com
          - name: AWS_BUCKET
            value: arn:aws:s3:::monolithic-microservices-bucket
          - name: AWS_REGION
            value: us-east-1
          - name: AWS_PROFILE
            value: default
          - name: JWT_SECRET
            value: testing
          - name: URL
            value: http://localhost:8100
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m