apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagram-reverseproxy
spec:
  selector:
    matchLabels:
      app: udagram-reverseproxy
  replicas: 2
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
      - name: udagram-reverseproxy
        image: jacobphelane/udagram-reverseproxy:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m